#!/bin/bash
if [ "$*" == "" ]; then
  echo "run peers initialPort"
  exit;
fi

osascript -e "tell application \"Terminal\" to do script \"cd $PWD && java -cp /Users/pramodchamala/IdeaProjects/CECS-327-Music-Player/lib/gson-2.8.5.jar:/Users/pramodchamala/IdeaProjects/CECS-327-Music-Player/out/production/CECS-327-Music-Player csulb.cecs327.DFS.DFSCommand.java $2\""

for ((i = 1; i < $1; i++));
do
port=$(($i + $2))
  osascript -e "tell application \"Terminal\" to do script \"cd $PWD && java -cp /Users/pramodchamala/IdeaProjects/CECS-327-Music-Player/lib/gson-2.8.5.jar:/Users/pramodchamala/IdeaProjects/CECS-327-Music-Player/out/production/CECS-327-Music-Player csulb.cecs327.DFS.DFSCommand.java $port $2\""

done
